### ISSUE TITLE
Flathub Version keeps crashing/closing

### ISSUE THREAD

**Issue by TrusterX** [flathub/net.wz2100.wz2100#19]
hi,

on my system, this flatpak running on Fedora 35 (X11) on Thinkpad X1 Extreme Gen3 (nvidia) keeps closing.

It is always reproducible. 
just run the latest savegame, take the squad and move into the base.
[savegames.zip](https://github.com/flathub/net.wz2100.wz2100/files/8156433/savegames.zip)

Snap version runs great without issues

Here ae the logs:
[cam1-3.0.log](https://github.com/flathub/net.wz2100.wz2100/files/8156449/cam1-3.0.log)
[WZlog-0228_210050.txt](https://github.com/flathub/net.wz2100.wz2100/files/8156450/WZlog-0228_210050.txt)
console output:
```
DEBUG: camSetEnemyBases: Base ScavBaseGroupSouth defined as empty group
/usr/include/c++/11.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = EDGE; _Alloc = std::allocator<EDGE>; std::vector<_Tp, _Alloc>::reference = EDGE&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Saved dump file to '/home/user/.var/app/net.wz2100.wz2100/data/warzone2100//logs/warzone2100.gdmp-3ApuZh'
```

is there something i can do?

**Comment by past-due** [comment]
@TrusterX This should be fixed in the latest releases, and a PR is open here to update the Flathub build: #20

(There are instructions in that PR for how to install a test build.)

**Comment by son-link** [comment]
@TrusterX If you can test the test build and verify that it works before the merge I would appreciate it.

**Comment by TrusterX** [comment]
looks promising - in a first short test-shoot, no crashes occurred. so i'll play this build now.
